# Generated by Django 2.0.7 on 2018-08-27 05:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0005_auto_20180823_1625'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={},
        ),
    ]
