# Generated by Django 2.0.7 on 2018-08-27 05:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0006_auto_20180827_1406'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'verbose_name': 'Profile', 'verbose_name_plural': 'profiles'},
        ),
    ]
