# Generated by Django 2.0.7 on 2018-08-28 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signup', '0009_auto_20180827_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='email_receive',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='profile',
            name='sms_receive',
            field=models.BooleanField(default=0),
            preserve_default=False,
        ),
    ]
